version: '3'

networks:
  nginx_net:
    external:
      name: nginx_net

services:
  website:
    container_name: "fumaz_web"
    image: fumaz/web-python
    build: .
    working_dir: /usr/src/app
    networks:
      - nginx_net
    volumes:
      - ./src:/usr/src/app
    command: python3 app.py